### ISSUE TITLE
Invalid Discord invite link

### ISSUE THREAD

**Issue by 20iyerd** [Merkie/freespeech#107]
**Describe the bug**
The invite link listed under the "Community" header in the readme (https://discord.gg/76PrNC6) is expired.

I have tried to join from both the app and the browser and the app, and both displayed the following screenshot.

![image](https://user-images.githubusercontent.com/35465486/125142507-e9d33e00-e0e5-11eb-8c2e-21db985846ae.png)

**Additional context**
I'm new to this community and would love to gain an understanding of the current work being done in order to contribute where necessary. Thanks!

**Comment by Merkie** [comment]
Hey I'm going to have to make a new Discord since the old one never really gained any members. Will update this thread later today when I have the new server.
