### ISSUE TITLE
Cannot see Add a Tile button in Chrome

### ISSUE THREAD

**Issue by MFerrulli** [Merkie/freespeech#112]
On the edit screen, running Chrome -
Version 96.0.4664.110 (Official Build) (64-bit)- Add a tile button is missing

**Comment by fatfingers23** [comment]
Hey, thank you for raising the issue! The button was temporarily removed for now. There was a bug that would not let anyone be able to save or add a new tile. This will be added back once the feature has been fully flushed out and re-implemented properly. Till then can take the current tiles and edit them to what you would like. Thank you! 


https://github.com/Merkie/freespeech/commit/6c6d6a46afd0dc1f902c5217a5f97649134bf6d4

**Comment by MFerrulli** [comment]
Thanks very much and thanks so much for this app. My dad has aphasia and is
very frustrated with his inability to communicate. This will help so much
with that problem and is simple enough that he can manage it - he is 91.

Mary
