### ISSUE TITLE
Clearing Navigation On Tile Edit Does Not Do That

### ISSUE THREAD

**Issue by fatfingers23** [Merkie/freespeech#115]
**Describe the bug**

Currently when you go to edit a tile. There is a remove navigation button. This only clears it on the form. but not inside of Vuex. Need to remove the property from the tile data for when it's added to Vuex so it will no longer be a navigation tile

**To Reproduce**
1. Turn on edit mode
2. Set navigation if not set
3. save
4. Re open as edit
5. Click remove navigation and save.
6. Does not actually remove it and still a navigation tile

**Expected behavior**
When its clicked and saved it removes navigation from the tileData property for that tile.

**Comment by Carlos-Gaxiola** [comment]
Hello, I created a PR that solves this issue to be reviewed
