### ISSUE TITLE
Divide Branches And Releases

### ISSUE THREAD

**Issue by fatfingers23** [Merkie/freespeech#119]
PRs #118 and #117  both have new features that we may not entirely be ready for production, but could still be pulled into the codebase.
I propose we make a `release` branch. It can be something like `release/x.x.x` for which version, or just `release-latest`. This will be clean production-ready code. If there needs to be a bug fix for production, we would create it and PR to the release branch and master. This will give developers a branch of code for us all to merge things that might not quite be ready for production but are ready for a PR while giving us a clean branch for bug fixes and cutting releases from. And then just releases will come from the release or releases branches.

If this sounds good I will set up the branches inside of this repo.

**Comment by Merkie** [comment]
Yeah sounds good.

**Comment by fatfingers23** [comment]
[releases/0.0.0.1](https://github.com/Merkie/freespeech/tree/releease/0.0.0.1) has been created and tagged. We can work out our versioning number system however we want. But usually, what we'll do here is if we get some bug fixes and need to push to the website, the new one will become 0.0.0.2. Or some people do year month. So 21.12.1. The last number is how many there has been that month. 

With this now we should be good to pull in the previous 2 prs if that works for you @Merkie and any that would be new features or experimental? We can then add the experimental button in master and move that code as it's a bit more mature.
