### ISSUE TITLE
New Editor

### ISSUE THREAD

**Issue by Merkie** [Merkie/freespeech#120]
We're going to have to expand the current editor to support some new features. 

I see two possibilities for this, the first one being a "safe" editor that will just work for any average user. This would likely consist of basically what we have now (editing tiles, adding navigation) along with a screen to manage different pages. The point of this would be that all pages are uniform. All pages are 5x12 tiles to utilize all screen space and standardize tile placements. Think of the app as typing on a keyboard, just with more buttons. If every page contained a different amount of buttons, the alignment would be off and users would have to really look at where they're typing. If all pages are 5x12, that wouldn't be an issue. Just as an example, we could standardize that the home/tiles navigation button will always be the bottom-right most tile. If all pages are 5x12 tiles, that navigation tile would always be in the same spot on the screen. If we made it so every page could have a different number of tiles, that uniformity would stop.

Another possibility is a "non-safe" editor that would give a lot more power to the users. Users could add/remove tiles at will, they could also do more powerful adjustments in the future. This gives more power to the end-user making the app more customizable, but you're risking a lack of uniformity and you're making the app more complex. I'm all down for supporting both, but I think the safe option should be the default.

Though, I think it's fitting to maybe adopt a ribbon-style editing menu like the one pictured. Would make the app feel more consistent and it would be easier to add new features I think. 

![editor](https://user-images.githubusercontent.com/18383101/147319292-277e758c-adbc-4774-9975-f3cb0bb6456b.png)

Let me know what thoughts you guys have on this and what features you think should be added. It's a difficult balance of maintaining an easy-to-use app and an app with all the customization users might want.

**Comment by Carlos-Gaxiola** [comment]
Hello, I want to work in this issue, but I have a couple of questions before working with it.

1.- If a non-safe editor is implemented, how will be the access to this view/editor, just by clicking an option that allow us to toggle between safe and non-safe editor?

2.- The functions that you show in the image, I mean the "Delete, Add, Pages, Import, Export, Save, Quit" options have to be working? Or for this issue just putting this menu and the possibility of toggling between the safe and non-safe editor is enough to solve the issue?

Thank you for your time, any doubt about my question, I am glad to answer

**Comment by Merkie** [comment]
Hey, thanks for your interest! Yeah, just a visual implementation is fine. A toggle in settings for "experimental editor" would work just fine. I'll attach all the icons I used in SVG format. Thanks! Please let me know if you have any questions.
[icons.zip](https://github.com/Merkie/freespeech/files/7790794/icons.zip)

**Comment by Carlos-Gaxiola** [comment]
Thank you, I will be working with this :)

**Comment by Carlos-Gaxiola** [comment]
Hello :) I have a question, about the icons, I can see you are using material design icons in the project, but in this case, you attach me some icons, should I look for similar icons in material design icons or should I add these icons in a folder and use inside the project?

**Comment by fatfingers23** [comment]
Hey @Carlos-Gaxiola. [Icon8](https://icons8.com) has been kind enough to give us a license to use their icons. So you can place those attached in the public directory and use them.

**Comment by Carlos-Gaxiola** [comment]
Nice! Thank you for your quickly response

**Comment by Carlos-Gaxiola** [comment]
Hello! When I was attaching the SVG Icons in the menu, I noticed the zip you provided to me has only has 5 Icons, the Icon for the "Save" and "Quit" options are missing, do u have the Icons? Or can I search it directly in the Icons8 page?

**Comment by Carlos-Gaxiola** [comment]
Hello, I finished this issue, I added the menu and the toggle to activated and maintain the 5X12 pages, the only thing missing are the Icons that I mentioned before, the "Save" and "Quit" options. Should I wait the icons or should I create the PR without these Icons?
