### ISSUE TITLE
Failing to compile because of missing modules

### ISSUE THREAD

**Issue by Code2Joke** [Merkie/freespeech#13]
freespeech-master % npm run build
> freespeechvue@0.1.0 build /Users/patrick/Downloads/freespeech-master> vue-cli-service build
⠦  Building for production...
 ERROR  Failed to compile with 2 errors                 20:44:13

This dependency was not found:

* !raw-loader!../../../README.md in ./node_modules/cache-loader/
dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/vuetify-loader/lib/loader.js??ref--18-0!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/About.vue?vue&type=script&lang=js&
To install it, you can run: npm install --save !raw-loader!../..
/../README.md

This relative module was not found:

* ../../../build.json in ./node_modules/cache-loader/dist/cjs.js
??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modu
les/babel-loader/lib!./node_modules/vuetify-loader/lib/loader.js
??ref--18-0!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./
node_modules/vue-loader/lib??vue-loader-options!./src/views/Tile
Pad.vue?vue&type=script&lang=js&
 ERROR  Build failed with errors.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! freespeechvue@0.1.0 build: `vue-cli-service build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the freespeechvue@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/patrick/.npm/_logs/2020-02-17T19_44_13_385Z-debug.log

**Comment by fatfingers23** [comment]
I would hold up till #12 is merged. Once it is merged can build by going to the VueApp directory and running `npm run install` then run `npm run build` or `nom run serve` to launch a dev environment.

**Comment by Merkie** [comment]
Yes this was fixed about an hour ago. Everything should build just fine if you redownload the repo.

**Comment by Code2Joke** [comment]
Another error code:
freespeech-master % npm install
npm WARN saveError ENOENT: no such file or directory, open '/Users/.../Downloads/freespeech-master/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/Users/.../Downloads/freespeech-master/package.json'
npm WARN freespeech-master No description
npm WARN freespeech-master No repository field.
npm WARN freespeech-master No README data
npm WARN freespeech-master No license field.

up to date in 1.898s
found 0 vulnerabilities

...@...-MBP freespeech-master % npm run build
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /Users/.../Downloads/freespeech-master/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/Users/.../Downloads/freespeech-master/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/.../.npm/_logs/2020-02-17T20_01_08_596Z-debug.log

**Comment by fatfingers23** [comment]
are you running these commands in the context of the vueapp folder? It looks like you are trying to run them on the root folder of the repo.

**Comment by Code2Joke** [comment]
That was it. Now it compiled! How do I run it though?

**Comment by fatfingers23** [comment]
If you do `npm run serve` it should host it at https://localhost:8080, or `npm run build` builds it to /vueapps/dist folder and you can host that on a web server.

**Comment by zoutepopcorn** [comment]
sudo -rf / plaatjes

Will work
