### ISSUE TITLE
Site doesn't load

### ISSUE THREAD

**Issue by ChildishGiant** [Merkie/freespeech#151]
**Describe the bug**
On both firefox and chrome on multiple devices the site doesn't load anything.

**To Reproduce**
Go to https://freespeechaac.com/ and open the dev console to see the issue.

**Expected behavior**
The page should load

**Screenshots**
![image](https://user-images.githubusercontent.com/13716824/203916675-97d492e4-6e31-4638-8827-3832c7a24005.png)
![image](https://user-images.githubusercontent.com/13716824/203916699-6b4afe1a-e6c7-4d9c-bb0a-e2ce53cf20d5.png)

**Desktop (please complete the following information):**
 - OS: Android,
 - Browser: Firefox 106, Chromium 106

**Comment by Merkie** [comment]
I'll notify this thread when the site is back online
