### ISSUE TITLE
look into relying less on tailwind colors for UI and using custom named colors like "bg-surface-x"

### ISSUE THREAD

**Issue by Merkie** [Merkie/freespeech#163]

**Comment by Shackless** [comment]
Do you need this for refactoring purposes / code cleanup or do you want to switch these colors based on themes etc.?
You can just define custom colors in your `tailwind.config` like described [here](https://tailwindcss.com/docs/customizing-colors#using-custom-colors). These can have shades and also named variants like this: 

```js
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    colors: {
      // ...
      'tahiti': {
        light: '#67e8f9',
        DEFAULT: '#06b6d4',
        dark: '#0e7490',
      },
      // ...
    },
  },
}
```
