### ISSUE TITLE
use github actions + now.sh to automatically publish

### ISSUE THREAD

**Issue by cyberhck** [Merkie/freespeech#18]
I can contribute to this if you're interested, now.sh uses lambda function, and it should be almost free as you have service worker implemented, (even if not, depending on how many users, it should still be cheap)

**Comment by cyberhck** [comment]
you can merge #19 even if you don't want to use now.sh, that's just basic preparation step which will help you for further contributions

**Comment by cyberhck** [comment]
hello @Merkie will you be willing to accept a PR which sends your production build to now.sh host now that you have a CI pipeline?

I can help setup domains and auto publishing from master branch :)

**Comment by fatfingers23** [comment]
Is this what you're talking about [now.sh](https://zeit.co/)? Looks pretty sweet, can point custom domains to it and even use serverless functions for free? Be nice for CI pipeline to run tests(once added) and check everything out before deploying.  I don't think this project would hit any of the limits either in the free tier.

**Comment by cyberhck** [comment]
yeah, that's exactly what I was thinking about, since it's static and if the service worker is deployed correctly, we won't even hit a lot of requests, OR (can't believe why I didn't think of it)
how about publishing to github pages instead? we can even use the github.io url, (or CNAME is supported anyways) (github.io url will also give a https url)

please let me know what you want to go with, doing a github actions will even be more easy as all we need to do is build and publish the built artifact to gh pages branch :)

**Comment by fatfingers23** [comment]
Sweet! I think Now.sh would work perfectly for what we want and gives us serverless functions if we ever need them. 

I'm all for it and think it'll be great. @Merkie has the final say on this though, cause i know he already has a host. But i think this solution would save us money and give us a lot of features. 

Only things i ask for is:
- Guards that run unit tests and checks lint on pr. Cannot be deployed or pr accepted till both pass.
- The account is setup by myself or Merkie for now.sh

Other than that I'm all for it. Adding the GitHub actions for this once we make a decision would be a great contribution and be greatly appreciated! Thank you so much for your help with all of this and the information you shared on it!
