### ISSUE TITLE
Please add the ability to copy your end result

### ISSUE THREAD

**Issue by thingyforthingy** [Merkie/freespeech#183]
Make it so you can copy the text of the end result of the aac so it goes into your clipboard

Make it so you can copy the end result of the aac:

![rthserfgdfgserg](https://github.com/Merkie/freespeech/assets/152095024/12fd0b60-b241-40eb-a026-f2f20bce2edb)

Please add a button for copying so its easy to do.

Here's an example for how it'd look:

![rfgjhsfghsfgserd](https://github.com/Merkie/freespeech/assets/152095024/69f19e16-6b9e-4244-97d3-cae90a754b4f)

Reason why this is needed:

Some aac ussers use aac's to text and having a copy button makes that a lot easier

**Comment by Merkie** [comment]
Sorry, I meant to close the branch not this issue! I went ahead and added your suggestion thank you :) 

https://github.com/Merkie/freespeech/assets/18383101/6bc62864-7dd5-4419-9d43-a647d3cf48b4

I went ahead and attached a video so you can see how it works. If you navigate to https://www.freespeechaac.com/app/dashboard/settings/behavior and enable the setting `Display "Copy Sentence" button` it will show that green copy button in the sentence builder and work like you'd expect!

Please let me know if you have any other suggestions, Thanks!
