### ISSUE TITLE
Missing package.json file

### ISSUE THREAD

**Issue by shivendrasinghtanwar** [Merkie/freespeech#20]
After the latest commit I think along with node modules package.json was also deleted.
I just cloned the repo and saw that no package.json file is present

**Comment by fatfingers23** [comment]
It’s still there. Are you running the npm commands in the context of the vueapp directory?

**Comment by fatfingers23** [comment]
package.json is under the vueapp folder. Not the root project folder.

**Comment by fatfingers23** [comment]
package.json is under the vueapp folder. Not the root project folder.
