### ISSUE TITLE
List Of Voices Do Not Populate On Google Chrome Desktop

### ISSUE THREAD

**Issue by fatfingers23** [Merkie/freespeech#21]
Under settings the select box to select a different voice does not get populated. This needs to be fixed in a way that does not break this functionality in other web browsers. Mainly IOS safari.

![image](https://user-images.githubusercontent.com/20476157/74739391-58c4a400-521e-11ea-96bb-6a4723177f35.png)

**Comment by reesdraminski** [comment]
I found this [StackOverflow post](https://stackoverflow.com/questions/49506716/speechsynthesis-getvoices-returns-empty-array-on-windows) that states that getVoices() is async so if you wrap it in a promise it would be a better flow
