### ISSUE TITLE
Button layout customization

### ISSUE THREAD

**Issue by MatthewSH** [Merkie/freespeech#31]
Having the ability to have buttons is great, but sometimes there may be a need to make more common buttons, like Yes or No, a bit bigger than others. Maybe there should be way to customize the layout of buttons such as normal, wide, tile options and customize the order of them as well.

**Comment by zeketx** [comment]
Great point! I used to work with augmentative and alternative communication (aac) devices for about 6 years as a therapist. The more pressing issue is the logic behind the software. A 3-year-old learns differently than let's say than 5-year-old (given cognition ability). The ability to customize layouts dependent on language barriers is key. That being said, I would love to be able to help in any capacity that is needed.
