### ISSUE TITLE
Button tap logging

### ISSUE THREAD

**Issue by MatthewSH** [Merkie/freespeech#32]
For parents/caretakers, it may be useful to understand how their user it actively using the apps, maybe having a report tool to tell us how often the buttons are being clicked could be useful, nothing too advanced...just simple counters for each button so they know which buttons are used the most and which can be replaced with new buttons due to lack of usage.

**Comment by gga1002** [comment]
Here's what I think could work  [video](https://www.loom.com/share/4aa8d248c9d84cb5b8ae25c76573e237)

I'm just missing the unit tests

**Comment by gga1002** [comment]
Here's another [video](https://www.loom.com/share/f6fd1a2e63c74611979559ac67a563e1) taps will only be logged until user click on Speak Button

**Comment by fatfingers23** [comment]
closed in #89
