### ISSUE TITLE
Allow more than just image location for buttons

### ISSUE THREAD

**Issue by MatthewSH** [Merkie/freespeech#33]
Haven't looked to see if this has been added, but why not add multiple button icon sources such as Font Awesome to present a more consistent feel for the user.

**Comment by fatfingers23** [comment]
I think this would be a great addition and is on the road map for sure. Ability to upload your own picture along with a library selection from different resources, and maybe even some of our own from contributions.

**Comment by MatthewSH** [comment]
I think a good first step for sure is to add Font Awesome or some other library (I just know FA5 free has A LOT of good options). I'll see if I can work on a PR later for this. Should be a pretty easy implementation for it, just have an setting for type of icon that you can switch through.
