### ISSUE TITLE
Guarding settings/add button routes

### ISSUE THREAD

**Issue by MatthewSH** [Merkie/freespeech#35]
Kids like to press buttons, some more than others...maybe it would be a good idea to allow caretakers/parents to restrict access to features such as add/edit buttons, settings, etc with a 4/6 digit passcode. Once entered, it can be locked immediately, or after a set time so they can edit and save settings without worrying about the child messing up the setup.

**Comment by fatfingers23** [comment]
PR #44 solved this.
