### ISSUE TITLE
research how swiftkey keyboard prediction and other similar tools work

### ISSUE THREAD

**Issue by cyberhck** [Merkie/freespeech#39]
maybe it'd be a good idea to help with prediction while typing? I might give this a go after a while if I get some time :)

**Comment by samwightt** [comment]
Actually know a little bit about this! So basic prediction software uses something called [Markov chains](https://en.wikipedia.org/wiki/Markov_chain), which are basically a probabilistic state machine (kinda like what [XState](https://github.com/davidkpiano/xstate) does but where you move randomly from one state to another via a probability). Keyboard prediction tools set each word as a node in the state machine, then go through each node and use some counting algorithm to link each node to words that come after that node and assign probabilities to it. This is usually done by analyzing a bunch of text. So for instance, if a computer analyzed text and saw the word 'hot' and saw the word 'dog' coming after it a lot, the _link between 'hot' and 'dog' would get a higher probability_. Still a bit rusty on how exactly those probabilities are assigned though. Hope this helps!

**Comment by cyberhck** [comment]
I'd love it if we could find this as a docker image, that'd help a lot (or even basic thing like only word completion would also help initially)

**Comment by samwightt** [comment]
There shouldn’t really be any need for a docker image, you can probably
just use something like this:
https://medium.com/@alexkrameris/markov-chain-implementation-in-javascript-a698f371d66f

**Comment by cyberhck** [comment]
but won't we need to store some data? (or you mean get the predefined data and load the whole thing on js?)

because if we store the data that'd mean it'll get better the more you use it.

**Comment by klues** [comment]
Take a look at my library "predictionary": https://asterics.github.io/predictionary/demo/
It uses a dictionary of the most common words for basic prediction and stores already typed sentences in order to suggest/predict them, if typed again.
