### ISSUE TITLE
Logo Suggestions

### ISSUE THREAD

**Issue by MatthewSH** [Merkie/freespeech#40]
Besides branding, I mean. It seems like it would be a nice thing to have, for favicons, app icons, etc.

[Logodust](https://logodust.com/) is a pretty good resource for commercial and noncommercial logos. 

I, personally, like [this one](https://www.dropbox.com/s/3ozg8hwvzrsgkwy/beek.svg?raw=1)

**Comment by Merkie** [comment]
Hm I will take a look. We have a logo guy right now, if he doesn't get back to me in a week I will throw out a few suggestions.
