### ISSUE TITLE
Add visual indicator when toggling edit mode

### ISSUE THREAD

**Issue by MatthewSH** [Merkie/freespeech#43]
When switching between edit mode and live mode there should be some way for the user to know (like an animation, or a navbar on top) to know their in edit mode...it's already happened to me. I thought I was in live mode and I was in edit mode.

**Comment by fatfingers23** [comment]
It's a bit more subtle and not the best icon. But the pencil icon is replaced with a save icon when you are editing tiles mode. I was thinking most of those icons need to be moved to a nav bar anyhow and could just have the pencil show when its in edit mode, and in the nav bar have a button to turn on edit mode.

**Comment by aidankinzett** [comment]
Might be good to add a small explanation of what you can do in edit mode, eg. tap to edit the tiles and drag to rearrange them

**Comment by fatfingers23** [comment]
Pr #49 solved these.
