### ISSUE TITLE
Add prettier support.

### ISSUE THREAD

**Issue by samwightt** [Merkie/freespeech#54]
**Is your feature request related to a problem? Please describe.**
My editor keeps changing tabs to spaces and not formatting code correctly, so it'd be great to have a prettier integration in here so I don't have to think about that.

**Describe the solution you'd like**
Integrate prettier into the project [like in this article](https://alligator.io/vuejs/vue-eslint-prettier/).

**Describe alternatives you've considered**
ES-Lint fix? Editor integration isn't that great though.

**Comment by fatfingers23** [comment]
I added PR #58 for what i think is best course for this.

**Comment by samwightt** [comment]
Looks perfect!
