### ISSUE TITLE
Discord?

### ISSUE THREAD

**Issue by MatthewSH** [Merkie/freespeech#56]
I think something like Discord could help grow the community and allow non-devs to interact with the code contributors and suggest ideas as well be more involved. Obviously it will be much smaller, but I think it could also open the road for discussion of features before they hit GH issues to allow the contributors to keep the issue board focused and clean along with helping contributors keep up with issue assignment and what they're working on so 2 people don't do the same thing. 

I've went ahead and created one myself as I have a good bit of experience with creating and managing these types of communities and with the help of @fatfingers23 (if he wants) we can setup GH/Discord webhooks to allow people within the Discord community to keep up to date on what's happening on the repo itself and new commits, releases, issues, and PRs happening.

https://discord.gg/DYRBJnh

Edit: At some point, I can transfer ownership of the server to whoever on the team.

**Comment by fatfingers23** [comment]
I like the idea of Discord. I was wondering about setting one up too. I'll see what @Merkie has to say about it.

**Comment by MatthewSH** [comment]
@fatfingers23 yeah, I'm in this one currently to use it as a template of what I've seen from successful projects in this community and help set it up to relieve @Merkie from any pressure in setting it up. It does exist if you wanna join from that invite to see what I'm talking about.

**Comment by edlinklater** [comment]
Just need to be careful to try and keep PR-related stuff out of Discord, as it can make things really messy for others to know whats going on if conversation about a PR happens outside of the PR. Have seen that happen before in other projects and it resulted in a big drop in contributions.

**Comment by Merkie** [comment]
I will make a Discord today when I get home

**Comment by MatthewSH** [comment]
I definitely understand, and that's where carefully designing channels to encourage PR related discussion limited to PR or specifying rules for that kind of stuff can be really successful. Example: Pterodactyl.io

There is a community of thousands of users but the contributions haven't changed because there is still plenty of discussion.

@Merkie I have one setup if you just wanna join and I can transfer ownership. Has some basic channels and roles setup for you to use.
