### ISSUE TITLE
Multiple Keyboards

### ISSUE THREAD

**Issue by fatfingers23** [Merkie/freespeech#60]
**Describe the solution you'd like**
I would like to see multiple custom keyboards. These can be stored and selected via settings page.

**Comment by MatthewSH** [comment]
I think this would be blocked by #50, would it not? I feel like at some point we'd be growing too large for localstorage and should just have that backend.

**Comment by fatfingers23** [comment]
I don't think so.  I mean yes and no. I'm seeing the smallest limit of local storage size is 5-10mb. Keyboard object is coming in under 20kb. I don't know if caching plays into that limit of size or not. I think maybe having 3 custom keyboards to start off is good till we get a backend.

**Comment by ariadnimac** [comment]
At the settings section there could be a "create custom keyboard" button and the standard keyboard appears so the user can color and put in different positions the tiles as he/ she wants to. And when they return home the keyboard has changed. However I' m not sure if backend would be needed for that.

**Comment by fatfingers23** [comment]
That is the current idea for now. We have where you can have one custom keyboard. But want to have multiple ones so users can try out different things without losing their previous keyboards. Right now we just store the one locally. Once we add a backend we'll connect it to that. We want to have a community place where people can post keyboards and share them with one another eventually.

**Comment by klues** [comment]
Regarding local storage you can use [IndexedDB](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API) which offers nearly unlimited storage. I'm using it for our AAC project [AsTeRICS Grid](https://github.com/asterics/AsTeRICS-Grid), with [PouchDB](https://pouchdb.com/), which makes IndexedDB access easier. I'm storing everything there (also images) - no problem. PouchDB also can be easily synced with [CouchDB](https://couchdb.apache.org/) running on a remote server.
See the implementation of my storage logic here: https://github.com/asterics/AsTeRICS-Grid/tree/master/src/js/service/data
