### ISSUE TITLE
GitHub Actions That Check Link And Test. 

### ISSUE THREAD

**Issue by fatfingers23** [Merkie/freespeech#66]
**Is your feature request related to a problem? Please describe.**
This would save time reviewing pull requests and help with the quality of the code we pull in.

**Describe the solution you'd like**
I would like for the lint section to just check. Not automatically lint their branch.
For testing i would like for it to request the author to take a look and block accepting the pr till test pass.

**Describe alternatives you've considered**
If a warning can't be made for linting then it automatically doing it for them works for me.

**Comment by MatthewSH** [comment]
Title: Check Link?
