### ISSUE TITLE
Draft Overview Of Techincal Needs From A Backend

### ISSUE THREAD

**Issue by fatfingers23** [Merkie/freespeech#72]
**This is a rough draft of technical aspects of a backend i would like to see us choose.  I know not everything on this list is possible, but it is high points to help us decide on what framework to use. This is a very very picky list. But I'm willing to bulge on most if you have a good solution to counter what i put.**

## Over all about the framework.
- Must be a modern web framework. I don't wanna see any VB.NET with WCF or PHP 5.6 /s 
- The backend will be a RESTFUL Json api. We will not be serving any views/guis/Vue components from this. The front end and backend will be different projects that can work together and can be decoupled.  
- Designed in a way that can be consumed by Vue project or any other project that we may add in the future. e.g. Mobile apps. 
-  Follows a MVC, MVVC pattern. Preferably MVVC. I like ViewModels, makes it clean and easy for the view to consume i personally think.
- Support for saving files in a secure way. E.g. pictures. We will probably use something like AWS or Azure blob storage i would imagine? 

## Deployment/ Dev environment 
- Can be hosted cheaply in the start. I'm talking free serverless or under 30 a month. 
- Can scaled to multiple instances. Not to worried about this in the start with scaling to multiple. instances. But want to keep it in mind and be prepared. 
- Full CI/CD pipeline support from GitHub actions or other free/included in the price. Also well documented resource. 
- I don't want to see anything that comes with a 5 page setup documentation for production that includes having a file that is in the repo, but i have to ssh to the server and change credentials in  that file. Full automation, i want it to push and deploy with no intervention. 
- Cross platform support. This means Windows, Linux, and macos. The code will more than likely be ran from a Linux server, but i want windows users to be able to contribute as well.
- Dead simple docker setup on initial pull to master. I see us having a backend branch while getting it all setup. I also see backend being a much higher level of entry to contribute then the front end. BUT i do not want that to stop our front end contributions just cause someone can't get the code to read from their sql server. I want like one command and minimal changes to a env file for developers to get a instance of the backend up and running and they can get to doing front end without even thinking about the back end. 
- If we pick serverless has to be in a way we can all design the backend on a free tier of a service. 
- Something the majority of the current contributors are comfortable with or are willing to learn. e.g. May not be your first choice. But you know it and have worked in it before 
- Must have unit testing support. This is an open source project and we will not have the luxery of QA testers to regression test.
- Familiar and popular language.
- Something with great documentation and stackover flow presence   

## Database support
- Must be model base/code first with migration support. Will find me hard press to move on this. We're not going be doing a ssh in and "Run this line of SQL before the update". Nope. 
- An open source/ license free database. Sorry guys no MSSQL here. Don't think it was even in yalls mind, but you never know.🤷‍♀️

## Security
- Solution for XSS scripting protection  
- SQL injection prevention/ parameterized sql statements.
- A secure and modern password hashing algorithm.
- Auth0/JWT support. Bonus if it handles refresh tokens. 
- I don't really want to see any self rolled security. Like some GitHub dependency with 5 stars that handles password hashing. These frameworks have already made these solutions lets use them. 

## Things that would make it faster and us all happy. 
- Premade methods. I'm talking the whole 9 yards you find in any popular frame work
  - email confirmation tokens generation
  - users with authentication 
  - built in roles
  - and so on. Almost anything you would see in a modern framework.

I'm open to all suggestions and discussion on this. I want it to be a group decision. Preferably majority decide on something.  I know this is a big list and a little extreme, but as a professional software developer I've worked with PHP with no framework, Python micro frameworks, SOAP services, Django, Laravel, and dotnet core are just a few i've worked with. I've seen the good, the bad, and the failed deployment at 3am that left the site down. I want this to be a great product and will hold it to a high standard. 

So with all of that said. Have a framework in mind? Great! Comment it below with a good constructive reason to why we should use it. See a comment someone made and you like that frame work? Follow these responses.

- 👍 I think this is a great framework to use and hits all the high points. I may of not used it before but i'm willing to go with it.
- ❤️  I love this framework, i use it daily or enough that i can program in it and help others. 
- 👎  I do not feel like this will fit the bill.
- 😦 if someone says we should use Cobol. 

If you have feed back for someone on their framework. Mention them, name what the framework is and give your constructive feed back or ask them to expand on it or give examples.

I do not want to see this as a talk down to any framework. All popular modern frameworks will more than likely fit this bill in one way or another. They all bring great things to the table and leave some behind. There will never be a perfect solution. Just looking for the best one and the one that is the most fun for us to code.

**Comment by ntindle** [comment]
I’m gonna throw Django into the ring. Specify Django Rest Framework. I think it covers all of the requirements

**Comment by fatfingers23** [comment]
I love Django. I've never used it for production, but it for sure hits all the high points. I was also kinda thinking about Express.js. Spent some time reading up on it and seems like it hits them as well. With Express i was thinking that almost because of we already all have NPM and would just need a docker/mysql db running. But honestly i imagine most people also have Python installed and can always put the whole backend into a docker image for people who only want to contribute to front end. I like it! Thank you.

**Comment by CallumGilly** [comment]
Just thinking about the security side of things, could it be a good idea to handle passwords and accounts through google as that keeps accounts secure without much moderation/ chance of leaks from free speech as well as not requiring much database space on the backend.

**Comment by fatfingers23** [comment]
I think we’ll probably use Auth0 with whatever backend we go with for authentication. It has packages to work with any major programming languages. 
https://auth0.com/

**Comment by TheFehr** [comment]
May I ask why the Rest requirement? I know I'm totaly an outsider here. No contibutions so far, but I'm just wondering why not GrahpQL? If you start from 0 there is little that speaks for REST over GraphQL in my opinion.

**Comment by mkchung8** [comment]
Hello there! I am a full stack developer based in Arizona. I saw your project on tik tok and wanted to contribute to your application. I am skilled in the MERN stack and primarily interested in back end development. 
I think Express is a great option that covers most of your requirements that you are looking for. Scalable, fast, and efficient. Its easy for other developers to understand the code since it's all javascript. Express is fantastic for applications that interact and gather data from third party resources. 

I've successfully used Heroku to deploy several projects. Its convenient to be able to deploy your application by just pushing commits to the heroku git repository. It takes care of all the back end infrastructure. The scaling is pretty straight forward as you only need to specify the number of processing units required. You're also just using standard tools to build the application so you aren't locked in should you decide to migrate to another service. However, the premiums for high volume applications are pretty expensive but I assume that extreme traffic on this application isn't currently an issue. I think it would be a great place to start and you could move the app to a different platform later if need be. 

Auth0 is fantastic and easy to use, however keep in mind that it gets very expensive once you start to scale. 

Please let me know if I am able to help contribute to this project in any way! This is an amazing thing you are creating.

**Comment by fatfingers23** [comment]
Hey @mkchung8, I think express is probably going be the way we go. Keep it all js and lower entry level for anyone who wants to contribute., since they probably already know js. Plus I've been reading up on express and i think it fits the bill. Feel free to reach out to me on our Discord server or via my email in my github. Would love to go into more depth about this and get the wheels moving on the backend. Currently we're still ironing out for all just client release. But would love to get started on backend for later releases. Thank you!

**Comment by billsliu** [comment]
Nodejs is very slow, the new project should use Golang to build future project. Golang is thirty times better than Nodejs.
