### ISSUE TITLE
VPS Hosting

### ISSUE THREAD

**Issue by ChaseHall** [Merkie/freespeech#79]
Not necessarily an "issue" but just putting this here..

I can host a **free** VPS for this project. Capable of hosting a website or a backend, or literally whatever Merkie wants. Obviously I'd also setup SSL for him and everything. 

Much love for this project. <3

Edit: Some other things included

* 1 Gbps Symmertrical connection
* Unlimited bandwidth
* Project emails (info [at] freespeech [dot] net for example) with Web UI + IMAP/SMTP Support.

edit 2: didn't see that there was already a site up, offer is still up incase you guys currently pay for a vps..

**Comment by fatfingers23** [comment]
@ChaseHall  Hey Chase thanks for the offer! We currently have a VPS but looking to move to some other free options that have CI/CD pipeline support. Thanks again!
