### ISSUE TITLE
Language support

### ISSUE THREAD

**Issue by CallumGilly** [Merkie/freespeech#82]
I think it would be nice to make an interface to help add new languages and compile a JSON in a tab on the site that shows one section at a time and requests the word that it is and what the title should be for other languages, making it easier to add new languages. This would allow people adding languages to not have to mess around with JSON (like below) and possibly break it/ find it difficult.
` {
          "name": "Little",
          "text": "Little",
          "image": "https://img.icons8.com/officexs/64/000000/cursor.png",
          "id": 1,
          "accent": "white",
          "messages": {
            "de": {
              "name": "Klein",
              "text": "klein"
            }
          }
        },`
Might atempt to make a HTML mock up later to show in more detail.

**Comment by fatfingers23** [comment]
I like the idea and agree! I would love to see a mockup too, even if it is just hand drawn to get a better visualization of what you're thinking the UI would look like. Only things i'm worried about is currently this is not our final starting keyboard. So i would hate for someone to put effort into translating the keys for some of it to not be used. Also i worry about how if someone adds a new language it would only be for them and no real way for it to migrate to other users without some kind of backend service that connects all Freespeech apps togather and would need a vetting process. Thank you though for this! I think there is a need for this and would be an awesome feature. Just we may need to hammer out the details a little more before someone starts on it.

**Comment by CallumGilly** [comment]
Below can be found the mock-up for this feature (mobile size). Fully agree that this could wait till a more finalised keyboard is made as we don't want to waste peoples time. It also would be nice if this could connect to backend and have a vetting process in order to ensure that it is translated properly. I also like the idea you put forwards in discord for a settings translation section before conformation. I also believe (mostly as a result of the keyboard being non-finalied) that this could wait until phase 2. 
![LanguageSupport1](https://user-images.githubusercontent.com/43007634/75998278-7a00e200-5ef8-11ea-89ed-9e7b92f398b5.png)

**Comment by klues** [comment]
Maybe my solution for our AAC tool "AsTeRICS Grid" helps giving you some inspiration or ideas how your multiple language support could be implemented: https://youtu.be/QPqZlTSMR8U (the video is in German, but you can enable automatically translated subtitles, which should make it possible for you to understand it).
