### ISSUE TITLE
Cannot reload application from About or Settings view

### ISSUE THREAD

**Issue by jose-galvan** [Merkie/freespeech#90]
**Describe the bug**
Click on reload in browser from Settings or About view won't reload the page and displays 404 Page not found

**To Reproduce**
1. Go to 'https://app.freespeechaac.com' 
2. Go to Settings or About
3. Click on refresh in your browser
4. See error: browser will display 404 Page Not Found

**Expected behavior**
Application should reload page in underlying view. 

**Screenshots**
![image](https://user-images.githubusercontent.com/33644205/78507892-9dfa5200-7748-11ea-8135-03a011d3adae.png)

**Additional context**
Web server needs a rule to rewrite all incoming request for non static resources; It should always return index.html

**Comment by whitmer** [comment]
I believe this is the solution to this issue: https://router.vuejs.org/guide/essentials/history-mode.html#example-server-configurations
