### ISSUE TITLE
Ability to save sentences

### ISSUE THREAD

**Issue by fatfingers23** [Merkie/freespeech#93]
**Is your feature request related to a problem? Please describe.**
The ability to save sentences that are commonly used. I really do not have a great ui idea on how this is done. But i think would be a wonderful option. It would list sentences the user created and saved. While also giving them an easy ability to select them, sort, etc.

**Comment by JonathanGrant92** [comment]
#### Feature: save sentences.

* Include a save button to save sentence for later. 
* Save sentences and group by first, second, third, etc, words.
* A collapsible window suggests sentences for user to select from.

---
#### A UI proposal:

A possible position for button that expands to window is left of the **Sentence** header in the output box. Button expands to window that fills area to **Speak** button and down to horizontal separator, after which is the input layout.

Window has the area to list a couple suggested sentences, and captures strokes within area to scroll the list; filtered to current user input, as proposed below.

---
#### A proposal for a sentence suggestion algorithm:

1. User enters a sprite.
1. App filters list for saved sentences that match current phrase of sprites.
    * User finds desired sentence and selects it. Logic ends.
    * Else User repeats step 1.
1. App list was filtered to empty
    * App suggests sentences from many to at least 1 matches, ignoring the order of words.

---
#### Final Thoughts

* Constraints of current project; can we implement this without adversely affecting performance and experience
   * Some users may have difficulties navigating proposed addition.
      * So, should we simplify this proposal more? Can we?
* Is the proposal as a whole just feature creep?
    * **Revised Proposal:** 
       * Let user save a list of sentences.
       * List button is visible in the tiles window.
       * List button opens to new window with textboxes (tiles) of saved sentences. 
       * Select a sentence which pastes to the output with no audio. 
       * User can modify sentence as needed, then press **Speak**.
       
       _I actually like this revised proposal for its simplicity; should be much easier to implement and use, because:_
        * _Implementation should adhere to current functionality and appearance of gui._
        * _Sorts and filters are likely unnecessary for users' needs, so I recommend against implementation of potentially unnecessary features. We can add extra features later, if they are actually needed, after **save a sentence** feature is implemented._

**Comment by JonathanGrant92** [comment]
To clarify, I am interested in implementing this feature, but I have time constraints currently. So, I am open to collaboration and contributing to part of the implementation.

I am unlikely to implement this feature by end of June, due to summer classes. I have a couple free weeks between semesters in August, so I could work on this issue then. But I am likely being optimistic if I say I can finish the issue in August. :smile:

I am much more confident about making a well-tested pull request in December or January.

For now, I can follow the discussion here.
