### ISSUE TITLE
A way to stop the speaking early

### ISSUE THREAD

**Issue by X3llus** [Merkie/freespeech#98]
**Is your feature request related to a problem? Please describe.**
When you click on the speak button while it is speaking it will queue it up to speak again and if pressed by accident multiple times it will speak the number of times you pressed and can't be stopped

**Describe the solution you'd like**
Either a button to remove all talk speak commands from queue/stop a speak early or have the speak button not work whilst already speaking would help to make this more user friendly and less prone to user error

**Comment by jose-galvan** [comment]
This issue has been fixed in PR #100
